name 'pantry-workstation'
maintainer 'Petr Michalec'
maintainer_email 'epcim@apealive.net'
license 'all_rights'
description 'Installs/Configures pantry-workstation'
long_description 'Installs/Configures pantry-workstation'
version '0.1.1'

depends 'pantry'
depends 'users'
depends 'homeshick'
depends 'apt'
depends 'yum'
depends 'poise-python'
depends 'nodejs'
