name 'workstation'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures workstation'
long_description 'Installs/Configures workstation'
version '0.1.0'

depends 'users'
depends 'homeshick'
depends 'apt'
depends 'yum'
depends 'poise-python'
depends 'nodejs'
