name 'pantry-workstation'
maintainer 'Petr Michalec'
maintainer_email 'epcim@apealive.net'
license 'all_rights'
description 'Installs/Configures pantry-workstation'
long_description 'Installs/Configures pantry-workstation. Wrapper for chef/pantry cookbook. Installs software packages and performs additional initial tasks to configure clean workstation or user on server.'
version '0.1.1'

depends 'pantry'
depends 'packages'
depends 'users'
depends 'homeshick'
depends 'apt'
depends 'yum'
depends 'poise-python'
depends 'nodejs'
